version: "3.7"

services:
  elasticsearch:
    build:
      context: docker/elasticsearch/
    volumes:
      - ./docker/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./docker/elasticsearch/data:/usr/share/elasticsearch/data:rw
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx2g -Xms2g"
    logging:
      options:
        max-size: 50m
  logstash:
    build:
      context: docker/logstash/
    volumes:
      - ./docker/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./docker/logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5001:5001"
      - "8889:8889"
      - "8890:8890"
    environment:
      LS_JAVA_OPTS: "-Xmx2g -Xms2g"
    depends_on:
      - elasticsearch
    logging:
      options:
        max-size: 50m
  kibana:
    build:
      context: docker/kibana/
    volumes:
      - ./docker/kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    logging:
      options:
        max-size: 50m
